### ISSUE TITLE
Include Openshift Jenkins plugins

### ISSUE THREAD

**Issue by manuvaldi** [atSistemas/workshop-jbcn-2017#10]
Install Openshift plugins for Jenkins.

**Comment by manuvaldi** [comment]
openshift pipepile plugin is force to version 1.0.44. That version is supported by Jenkins-LTS Docker version.

**Comment by cmcornejocrespo** [comment]
Hola Manu,

Cuando levanto el stack, Jenkins se queja de los plugins de openshift:

jenkins_1           | SEVERE: Failed Loading plugin Pipeline: Job v2.12 (workflow-job)
jenkins_1           | java.io.IOException: Pipeline: Job v2.12 failed to load.
jenkins_1           |  - You must update Jenkins from v2.46.2 to v2.60 or later to run this plugin.
jenkins_1           |   at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:621)
...
jenkins_1           | SEVERE: Failed Loading plugin Pipeline Graph Analysis Plugin v1.4 (pipeline-graph-analysis)
jenkins_1           | java.io.IOException: Pipeline Graph Analysis Plugin v1.4 failed to load.
jenkins_1           |  - Pipeline: Job v2.12 failed to load. Fix this plugin first.
jenkins_1           |   at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:621)
...
jenkins_1           | SEVERE: Failed Loading plugin Pipeline: REST API Plugin v2.8 (pipeline-rest-api)
jenkins_1           | java.io.IOException: Pipeline: REST API Plugin v2.8 failed to load.
jenkins_1           |  - Pipeline: Job v2.12 failed to load. Fix this plugin first.
jenkins_1           |   at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:621)
....
jenkins_1           | SEVERE: Failed Loading plugin OpenShift Sync v0.1.16 (openshift-sync)
jenkins_1           | java.io.IOException: OpenShift Sync v0.1.16 failed to load.
jenkins_1           |  - Pipeline: Job v2.12 failed to load. Fix this plugin first.
jenkins_1           |   at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:621)
.....
jenkins_1           | SEVERE: Failed Loading plugin OpenShift Pipeline Jenkins Plugin v1.0.44 (openshift-pipeline)
jenkins_1           | java.io.IOException: OpenShift Pipeline Jenkins Plugin v1.0.44 failed to load.
jenkins_1           |  - OpenShift Sync v0.1.16 failed to load. Fix this plugin first.
jenkins_1           |   at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:621)
.....

Te re-abro el ticket, ok?

Gracias!

**Comment by manuvaldi** [comment]
Has probado a borrar volúmenes antes de levantar?
